# Generated by stackage2nix 0.7.0 from "/nix/store/n4zf5qpblb89zy18z6irlsvy42k40v30-stackage-all/lts-9.21.yaml"
{ callPackage, buildPackages, pkgs, stdenv, lib
, overrides ? (self: super: {})
}:

let
  inherit (lib) extends makeExtensible;
  haskellLib = pkgs.haskell.lib;
  inherit (haskellLib) makePackageSet;

  haskellPackages = pkgs.callPackage makePackageSet rec {
                      buildHaskellPackages = ghc.bootPkgs;
                      ghc = buildPackages.haskell.compiler.ghcjsHEAD;
                      package-set = import ./packages.nix;
                      inherit stdenv haskellLib extensible-self;
                    };

  packageSetConfig = import (pkgs.path + "/pkgs/development/haskell-modules/configuration-ghcjs.nix") { inherit pkgs haskellLib; };
  compilerConfig = import (pkgs.path + "/pkgs/development/haskell-modules/configuration-ghc-8.0.x.nix") { inherit pkgs haskellLib; };

  configurationCommon = import (pkgs.path + "/pkgs/development/haskell-modules/configuration-common.nix") { inherit pkgs haskellLib; };
  configurationNix = import (pkgs.path + "/pkgs/development/haskell-modules/configuration-nix.nix") { inherit pkgs haskellLib; };

  extensible-self = makeExtensible (extends overrides (extends packageSetConfig (extends compilerConfig (extends configurationCommon (extends configurationNix haskellPackages)))));

in extensible-self
